### ISSUE TITLE
DriveTrain needs setSpeed for Auto

### ISSUE THREAD

**Issue by AaronJacobson** [IronRiders/Recycle-Rush#1]
The Talon speed controllers are plugged into two ports one for the left and one for the right (3 per port).   We need a method to set the speed which accepts two parameters of type double which represent the speed for the left and right sides.

**Comment by johnluetke** [comment]
Here is last year's drive code for reference: https://github.com/IronRiders/Aerial-Assist-Code/blob/master/Aerial-Assist-Code/src/Team4180/Driving.java
