### ISSUE TITLE
Give Jason Dan access to GitHub issue list

### ISSUE THREAD

**Issue by organizefish** [IronRiders/Recycle-Rush#12]
Work with Jason to get him up and running on GitHub. This way our PM can track the progress of the software code, and provide support in managing this work.

Assign this issue back to me with Jason's GitHub username, and I'll add him to the student team of this GitHub organization.

**Comment by kcooper42** [comment]
jasondan1

**Comment by organizefish** [comment]
Added @jasondan1.
