### ISSUE TITLE
Assign software members to GitHub issues

### ISSUE THREAD

**Issue by organizefish** [IronRiders/Recycle-Rush#13]
@UltGuardian has uploaded the [software work summary schedule](https://drive.google.com/file/d/0B55KIOAn4kmTWFhWZXd2Q0wtWGM/view?usp=sharing) to Google Drive. Look through the [GitHub issues](https://github.com/IronRiders/Recycle-Rush/issues/) and assign each issue to the students who are responsible for them. You can assign issues to more than one person.
#### The following should probably be documented for reference...

The software team should utilize these issues to track their progress. Something awesome is that any time you reference an issue number from a commit message, the commit messages are added to the issue discussion.

If a software team member has a question, they should add the [question label](https://github.com/IronRiders/Recycle-Rush/labels/question) and assign the issue to the person they think can answer it.

If a software team member runs into an error or a bug, they should create a new issue. In this issue they should provide reproduction steps of the error, state what they expected to happen, and state what actually happened. Also helpful is what things they've tried so far to fix the error. Label this issue with the [bug label](https://github.com/IronRiders/Recycle-Rush/labels/bug).

**Comment by AaronJacobson** [comment]
I have assigned everyone to the tasks which were created initially.
