### ISSUE TITLE
Can't upgrade the RoboRIO firmware

### ISSUE THREAD

**Issue by organizefish** [IronRiders/Recycle-Rush#14]
Repro Steps:

Expected Result:

Actual Result:

**Comment by organizefish** [comment]
Assigned to @mashmouse, as this issue is waiting for her to update the description.

**Comment by johnluetke** [comment]
I spent some time today getting the rest of it set up.
- Updated the roboRIO firmware
- Installed Java on the roboRIO
- Configured the wireless bridge to broadcast the `4180` network.

**Comment by AaronJacobson** [comment]
I have uploaded code to the roboRIO and have gotten a motor to spin. However println statements don't seem to be working as they did last year.

**Comment by johnluetke** [comment]
Are you running the code from eclipse? I remember that was required.

If so, then it probably has to do with the roboRIO, and would require some investigation.

**Comment by AaronJacobson** [comment]
The original issue has been fixed the new issue is issue #27
