### ISSUE TITLE
Build Path Errors Fix needs to be applied to all computers in CAD Lab

### ISSUE THREAD

**Issue by overlordnate** [IronRiders/Recycle-Rush#16]
The Build path error fix needs to be applied to all of the computers in the CAD lab in order to let software work on robot code in eclipse. [Link to problem and problem fix](https://github.com/IronRiders/Recycle-Rush/issues/15)

**Comment by johnluetke** [comment]
Initially done in 65b82c494725a2e2807180315f1633742e93e8e2, refined in 4617709d868fa406e977b237c5da610dd9a88659 via #17
