### ISSUE TITLE
Elevator needs 6 limit switches

### ISSUE THREAD

**Issue by AaronJacobson** [IronRiders/Recycle-Rush#18]
The Elevator class needs one Level0LimitSwitch, 4 MidLevelLimitSwitches, and one Level5LimitSwitch. It needs to have a method where it updates their states.

**Comment by AaronJacobson** [comment]
The ports for the limit switches can be found [here](https://docs.google.com/a/appel-rockhold.org/spreadsheets/d/1-stbHsmSUjk-GcwQA7Wa-W1kXgtMiDb0FCNZL13Eang/edit?usp=sharing)

**Comment by johnluetke** [comment]
Be sure to define the port numbers in Port.java, per #9
