### ISSUE TITLE
Create a Button Interface

### ISSUE THREAD

**Issue by AaronJacobson** [IronRiders/Recycle-Rush#20]
We need a button interface which has a method for when the button is pressed and one method for when the button is not pressed.

**Comment by johnluetke** [comment]
https://github.com/IronRiders/Aerial-Assist/blob/master/Aerial-Assist-Code/src/Team4180/Listeners/ButtonListener.java

**Comment by DylanLaMarca** [comment]
Sorry that was me

**Comment by organizefish** [comment]
hahah. We be learning GitHub awesomely.

**Comment by johnluetke** [comment]
Do I want to know? :-)

**Comment by overlordnate** [comment]
How did you even close it twice  XD
