### ISSUE TITLE
Create Attack3Joystick

### ISSUE THREAD

**Issue by AaronJacobson** [IronRiders/Recycle-Rush#23]
Because we need more functions than the default joystick class we need to create our own. We need to use the same constructor as the default joystick constructor. It also needs an array of Buttons which we will use to track the button listeners we assign it.

**Comment by johnluetke** [comment]
You should be able to copy the code for this directly from last year.

https://github.com/IronRiders/Aerial-Assist/blob/master/Aerial-Assist-Code/src/Team4180/Input/Attack3Joystick.java

**Comment by johnluetke** [comment]
@GhoulPoP This class doesn't appear to do anything other that use the code that is provided by FIRST's joystick class

One of the benefit's of open sourcing the code from the previous year's competition is that we can re-use it in future competitions.

Copy the code file from last year (use the link I gave above).
