### ISSUE TITLE
Create a JoystickListener Interface

### ISSUE THREAD

**Issue by AaronJacobson** [IronRiders/Recycle-Rush#25]
This interface needs to have a method for when the joystick is moved and it needs to be able to take in the x y and z values on the joystick

**Comment by johnluetke** [comment]
Like #23, this can be copied from last year:

https://github.com/IronRiders/Aerial-Assist/blob/master/Aerial-Assist-Code/src/Team4180/Listeners/JoystickListener.java

**Comment by DylanLaMarca** [comment]
WWHHOOO, I made the JoystickListener Interface... it was pretty cool

**Comment by AaronJacobson** [comment]
I don't see a joystick listener in the repository, maybe you didn't commit and push?

**Comment by SuperiorNyx** [comment]
He fixed it
