### ISSUE TITLE
Can't use println statements on the RoboRio

### ISSUE THREAD

**Issue by AaronJacobson** [IronRiders/Recycle-Rush#27]
I have not been able to use println statements when working with the RoboRio and they are what I have been using for debugging.

**Comment by johnluetke** [comment]
[According to ChiefDelphi](http://www.chiefdelphi.com/forums/showpost.php?s=2be068808326280e1950028bd14eeada&p=1425644&postcount=3), `println` statements in Eclipse don't show by default like they do in NetBeans:

http://wpilib.screenstepslive.com/s/4485/m/13809/l/284333-using-riolog-to-view-console-output

**Comment by johnluetke** [comment]
What change specifically addressed this? All I see are printlns being removed?

**Comment by SuperiorNyx** [comment]
We just followed the instructions and moved some of the println statements to make it so they actually outputted into the riolog

**Comment by johnluetke** [comment]
Okay, that wasn't obvious to me in Aarons commit.

No worries, just trying to understand. The roborio is new to me too :-)
