### ISSUE TITLE
Missing Talon data type in the DriveTrain

### ISSUE THREAD

**Issue by overlordnate** [IronRiders/Recycle-Rush#28]
look here for the bug https://github.com/IronRiders/Recycle-Rush/commit/61e3d34ca657c03ac20377fe926471091d49f142#diff-e22f6610d937279f25c59af9d03fb80fR6

**Comment by imp-lux** [comment]
We also fixed this.
Jaron and Fiona

**Comment by organizefish** [comment]
Fixed in commit 721b122984c7c245389a21f1261b2a1c0e4d835f
