### ISSUE TITLE
missing jaguar data type in the ElevatorStart 

### ISSUE THREAD

**Issue by overlordnate** [IronRiders/Recycle-Rush#29]
look here for issue https://github.com/IronRiders/Recycle-Rush/commit/164d56080d332f2ab98993456b622195c674feb9#diff-53c247ea1e8f0ab0d17c129ce223f740R4

**Comment by imp-lux** [comment]
We fixed this too.
Fiona and Jaron

**Comment by organizefish** [comment]
Fixed in commit 721b122984c7c245389a21f1261b2a1c0e4d835f
