### ISSUE TITLE
Missing data type in the setSpeed method of ElevatorStart

### ISSUE THREAD

**Issue by overlordnate** [IronRiders/Recycle-Rush#30]
look here https://github.com/IronRiders/Recycle-Rush/commit/164d56080d332f2ab98993456b622195c674feb9#diff-53c247ea1e8f0ab0d17c129ce223f740R12

**Comment by imp-lux** [comment]
We fixed it.
-Jaron and Fiona

**Comment by organizefish** [comment]
Fixed in commit 721b122984c7c245389a21f1261b2a1c0e4d835f
