### ISSUE TITLE
CAD Lab Computers Are Missing Necessary Files 

### ISSUE THREAD

**Issue by finnegancarroll** [IronRiders/Recycle-Rush#31]
![issue instructions](https://cloud.githubusercontent.com/assets/7841487/5750205/596dc158-9c06-11e4-9492-f3408a4c89be.png)
- If the project is pulled from git hub it does not come with the jre library or frc plugins, and if you try to download and add them on the school computers in the CAD lab it will get errors. We were also unable to edit the build path or create new classes because the source folder wasn't a java project. 
- I expected that i would be able to pull the code, download and add the libraries and plugins to the C drive and compile the current code without errors.

**Comment by organizefish** [comment]
Fixed with commit b81d72dfcb6fcb8a2320a5a76f349a28dcee2d41. Sadly, while Git recognized that the libraries, dot files, and build.xml files were file moves, it did not recognize that the source files were simply moved so no history for the Java files. :(
