### ISSUE TITLE
MovementListener?

### ISSUE THREAD

**Issue by hallebit** [IronRiders/Recycle-Rush#34]
the drive code was not divided up into separate tasks, therefore I was wondering... are we going to have a MovementListener (which creates an DriveTrain object, calls updateX/Y, and the reCalcVelocity methods) ?
If yes, can I create an issue. If no, what are we making?

**Comment by hallebit** [comment]
johnluetke? UltGuardian?

**Comment by AaronJacobson** [comment]
For now that is what we are going to do, and yes you can create an issue for it.

**Comment by hallebit** [comment]
thank you
