### ISSUE TITLE
Update DriverStation and RoboRIO software BEFORE Glacier Peak

### ISSUE THREAD

**Issue by johnluetke** [IronRiders/Recycle-Rush#42]
Greetings Teams:

We have been notified that a significant number of teams do not have the correct versions of firmware and software installed before they get to inspection.  This is causing delays and frustration. Please make sure your robot has the required minimum versions from the Inspection Checklist:

Driver Station: 08021500 or newer (Note the version number is a date in the format of, DD/MM/YY00)

roboRIO – v23 and 2.1.0f3

Talon SRX – v.28 for PWM, v1.01 for CAN

Jaguars – v109

PCM – v1.62

PDP – v1.37

Any computer that has had the updated NI Update Suite (which also installs the latest Driver Station) installed should have up-to-date versions of all firmware installed.

RoboRIO Firmware - Installed to "Program Files\National Instruments\Shared\Firmware\cRIO\76F2\" Program Files(x86) on 64 bit
RoboRIO Image - Installed to "C:\Program Files (x86)\National Instruments\LabVIEW 2014\project\roboRIO Tool\FRC Images" where the imaging tool will look for it
All other firmwares - Installed to "C:\Users\Public\Documents\FRC"

More information about the latest versions, along with links to installation instructions can be found on our Current Software Revisions page.

**Comment by AaronJacobson** [comment]
We passed inspection which included the software updates.
