### ISSUE TITLE
PortHolder

### ISSUE THREAD

**Issue by AaronJacobson** [IronRiders/Recycle-Rush#8]
The PortHolder will be an enum called "Port". Some of the port numbers are the same because there are multiple sets of ports on the RoboRio
It will hold the following ports:
(DIO ports)
a limit switch for level 0 of the elevation system on port 0
a limit switch for level 1 of the elevation system on port 1
a limit switch for level 2 of the elevation system on port 2
a limit switch for level 3 of the elevation system on port 3
a limit switch for level 4 of the elevation system on port 4
a limit switch for level 5 of the elevation system on port 5
(PMW ports)
a Talon motor controller for the right side of the drive train on port 0
a Talon motor controller for the left side of the drive train on port 1
a Jaguar motor controller for the winch in the elevation system on port 2
(PCM ports)
a Solenoid for controlling the gearboxes on port 0
a Solenoid for controlling the forklift arm on port 1

**Comment by AaronJacobson** [comment]
updated the task, it's now an enum

**Comment by overlordnate** [comment]
Done with all of the above, will continue to update of _hardware_ changes ports
