### ISSUE TITLE
PortHolder needs to be renamed and changed to a 'public enum'

### ISSUE THREAD

**Issue by afitz0** [IronRiders/Recycle-Rush#9]
See comment in commit 167913e0d241bc67d4bcb624395e2bd1593e6cc0 for more info.

**Comment by johnluetke** [comment]
Unless it has changed with the new controller this year, they are using JDK 1.3, which doesn't support proper enums.

**Comment by AaronJacobson** [comment]
It was changed, we are now using JDK 8

**Comment by johnluetke** [comment]
Nice! In that case, I stand behind Fitz suggestion: Enums would be the best
approach to the "PortHolder"

**Comment by AaronJacobson** [comment]
Changed it.

**Comment by organizefish** [comment]
PortHolder.java is still named PortHolder.java, and is a class. This change requires the change to be pushed to the repo. This issue can only be closed by committing and pushing the corrected change.

FYI: I'm introducing a git workflow that doesn't allow you to close issues / commit/push changes without a code review. Please check in with @GhoulPoP regarding the gitflow workflow.
